# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(512, 376))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 58, 15))
        self.label.setObjectName("label")
        self.logs = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logs.setGeometry(QtCore.QRect(10, 30, 531, 281))
        self.logs.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.logs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.logs.setReadOnly(True)
        self.logs.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.logs.setObjectName("logs")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 335, 41, 16))
        self.label_2.setObjectName("label_2")
        self.port_textedit = QtWidgets.QTextEdit(self.centralwidget)
        self.port_textedit.setEnabled(True)
        self.port_textedit.setGeometry(QtCore.QRect(250, 330, 51, 30))
        self.port_textedit.setObjectName("port_textedit")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(320, 330, 93, 30))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setGeometry(QtCore.QRect(420, 330, 93, 30))
        self.stop_button.setObjectName("stop_button")
        self.about_button = QtWidgets.QPushButton(self.centralwidget)
        self.about_button.setGeometry(QtCore.QRect(520, 330, 30, 30))
        self.about_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_button.setIcon(icon)
        self.about_button.setObjectName("about_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 335, 58, 15))
        self.label_3.setObjectName("label_3")
        self.serverip_textedit = QtWidgets.QTextEdit(self.centralwidget)
        self.serverip_textedit.setGeometry(QtCore.QRect(70, 330, 131, 31))
        self.serverip_textedit.setObjectName("serverip_textedit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 25))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "client"))
        self.label.setText(_translate("MainWindow", "Logs:"))
        self.logs.setStatusTip(_translate("MainWindow", "目前伺服器的紀錄"))
        self.label_2.setText(_translate("MainWindow", "port:"))
        self.port_textedit.setStatusTip(_translate("MainWindow", "輸入要開啟的port"))
        self.port_textedit.setPlaceholderText(_translate("MainWindow", "12345"))
        self.start_button.setText(_translate("MainWindow", "開始"))
        self.stop_button.setText(_translate("MainWindow", "停止"))
        self.label_3.setText(_translate("MainWindow", "server ip:"))
        self.serverip_textedit.setStatusTip(_translate("MainWindow", "輸入server的ip"))
import icons_rc
