# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 347)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 58, 15))
        self.label.setObjectName("label")
        self.logs = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logs.setGeometry(QtCore.QRect(10, 30, 451, 211))
        self.logs.setReadOnly(True)
        self.logs.setObjectName("logs")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 266, 58, 15))
        self.label_2.setObjectName("label_2")
        self.port = QtWidgets.QTextEdit(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(60, 260, 131, 31))
        self.port.setObjectName("port")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(270, 260, 93, 28))
        self.Start_Button.setObjectName("Start_Button")
        self.Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Button.setEnabled(False)
        self.Stop_Button.setGeometry(QtCore.QRect(370, 260, 93, 28))
        self.Stop_Button.setObjectName("Stop_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 25))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "server"))
        self.label.setText(_translate("MainWindow", "Logs:"))
        self.label_2.setText(_translate("MainWindow", "port:"))
        self.Start_Button.setText(_translate("MainWindow", "開始"))
        self.Stop_Button.setText(_translate("MainWindow", "停止"))
